name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move build artifacts
        run: mv dist/ release/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and push release branch
        run: |
          git config --global user.name "anveloper"
          git config --global user.email "hitedin@gmail.com"
          git checkout -b release
          git add dist
          git commit -m "release: build"
          git push origin release
