name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 UTC 기준
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: anveloper
          outputs: dist/snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: contribution-snake
          path: dist/snake.svg
